defaults:
  - _self_
  - policy: ppo

ckpt_path:  null #'outputs/2024-11-07/10-49-13/checkpoints/model_900.pt' #'best_models/checkpoints/model_1500.pt' #'best_models/test_vic2_0810_1.pt' #'outputs/2024-10-04/16-03-35/checkpoints/model_1400.pt'  #'best_models/rando_all1.pt' #'best_models/test_vic2_jt_harder.pt' #'best_models/rando_all1.pt' #'best_models/test_vic2_jt_harder.pt' #'best_models/test_vic3_jt.pt' # 'best_models/test_vic2_bf.pt' # #'best_models/test_vic_2_20_1.pt' #'outputs/2024-09-19/16-56-36/checkpoints/model_2000.pt' #'best_models/test_vic1.pt' #'best_models/test_vic_2_oldpose.pt' #'best_models/test_pos_priv.pt' # # #'best_models/test_p_oldpose.pt' # #  # #'outputs/2024-09-16/18-45-14/checkpoints/model_2000.pt' # ## #'best_models/test_vic1.pt' #

env:
  action_scale: 0.3
  action_stiff_scale: 1.0
  hip_scale: 0.5
  control_mode: "P"
  physics_steps_per_control_step: 4
  sample_command_interval: 301

  num_history_actor: 5
  num_history_critic: 1
  kick_vel: 0.0
  push_interval: 25

  # Force kick in test
  enable_force_kick: False
  impulse_force_kick: False

  force_kick_duration: 0.1
  force_kick_impulse: [20.,20.]
  force_kick_interval: 150
  kick_force: 600.0

  is_training: False
  episode_length: 3250

  single_obs_size: 48
  single_obs_size_priv: 59
 

  domain_rand:
    randomisation: False
    gravity_offset: [-0., 0.]
    friction_range: [1., 1.]
    payload_range: [0., 0.]
    hip_mass_range: [0., 0.]
    kp_range: [1., 1.]
    kd_range: [1., 1.]
    motor_strength_range: [1., 1.]

    local_v_noise: 0.1
    local_w_noise: 0.2
    joint_noise: 0.01
    joint_vel_noise: 1.5
    gravity_noise: 0.05

  normalization:
    local_v_scale: 2.0
    local_w_scale: 0.25
    joint_vel_scale: 0.1
    command_scale: 2.0
  
  control_range: {
    'cmd_x': [-1.5, 1.5],
    'cmd_y': [-1.5, 1.5],
    'cmd_ang': [-0., 0.]
  }

  manual_control:
    enable: True
    task: 'auto' # can be either 'auto', 'force_push', 'heading_directions','test_xy_random' , 'escape pyramids' ,'track trajectory', 
    cmd_x: 0.3
    cmd_y: 0.0
    cmd_ang: 0.0

  reset_pos_x: [-0.0, 0.0]
  reset_pos_y: [-0.0, 0.0]

  control:
    stiff_range: [0.5, 1.5]
    p_gain: 50.0
    d_gain: 1.0
  
  reward_scales: { 
          'tracking_lin_vel': 1.5, 
          'tracking_ang_vel': 0.8, 
          'lin_vel_z': -2.0, 
          'ang_vel_xy': -0.05, 
          'orientation': -5.0,
          'stand_still': -0.5, 
          'feet_air_time': 0.5,
          'termination': -10.0,
          'foot_slip': -0.1,
          'action_rate': -0.002,
          'rew_pos_limits': -0.02,
          'rew_stiff_limits': -0.02,
          'rew_acceleration': -2.5e-7,
          'rew_collision': -10.0,
          'rew_power': -2.e-5,
          'rew_power_distro': -5.e-6,
          "hip": 0.05,
          'rew_joint_track': -0.1,
          'rew_foot_clearance': -0.01,
  }
 
success_threshold: 0.78125
rollouts_per_experiment: 8
plot_details: True

result_name: 'results_vic2_0810.csv'
timesteps_per_rollout: 50
num_iterations: 65
num_envs: 1

viz: True
device: 'cuda:0'
curriculum: False
scene_xml: 'unitree_go2/flat.xml'