defaults:
  - _self_
  - policy: ppo

env:
  action_scale: 0.3
  control_mode: "P"
  physics_steps_per_control_step: 20 # corresponds to 50Hz
  obs_noise: 0.
  num_history: 1 # corresponds to 0.3s
  kick_vel: 0.1
  push_interval: 50
  is_training: True
  manual_control: False

log: True
ckpt_path: "best_models/model_1950.pt"
#ckpt_path: null
log_dir: "Documents/TALocoMotion/outputs/"

num_envs: 200 
episode_length: 100
num_learning_iterations: 5001
device: 'cuda:0'
viz: True

project: PositionControlled
group: Bruce-P2
scene_xml: 'unitree_go2/terrain_new.xml' 
