defaults:
  - _self_
  - policy: ppo

env:
  action_scale: 0.3
  control_mode: "P"
  physics_steps_per_control_step: 4 # corresponds to 50Hz
  obs_noise: 0.0
  act_noise: 0.0
  num_history: 1 # number of previous observations to stack
  kick_vel: 0.15
  push_interval: 50
  is_training: True
  manual_control: False
  cmd_x: 0.8
  cmd_y: 0.0
  cmd_ang: 0.0
  episode_length: 1000


log: True

#ckpt_path: 'outputs/2024-07-22/09-38-47/checkpoints/model_3000.pt'
ckpt_path: null

log_dir: "Documents/TALocoMotion/outputs/"


num_envs: 4096 

timesteps_per_rollout: 24
num_learning_iterations: 2001
device: 'cuda:0'
randomisation: False
curriculum: False
viz: False

project: PositionControlled
group: Bruce-P2
scene_xml: 'unitree_go2/flat.xml' 
